{% set name = "libvulkan-headers" %}
{% set version = "1.3.296.0" %}

package:
  name: {{ name }}
  version: {{ version }}

# For this repo, v**** tags exists, but apparently the stable tags (the one corresponding to versions
# that are available for download at https://vulkan.lunarg.com/sdk/home) are the vulkan-sdk-*** ones
# See https://github.com/KhronosGroup/Vulkan-Headers#version-tagging-scheme
source:
  url: https://github.com/KhronosGroup/Vulkan-Headers/archive/refs/tags/vulkan-sdk-{{ version }}.tar.gz
  sha256: 1e872a0be3890784bbe68dcd89b7e017fed77ba95820841848718c98bda6dc33

build:
  number: 0

requirements:
  build:
    - cmake
    - ninja
    # This is just required to make sure that ${CMAKE_ARGS} is defined
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}

test:
  commands:
    - test -f ${PREFIX}/include/vulkan/vk_icd.h  # [not win]
    - if not exist %PREFIX%\\Library\\include\\vulkan\\vk_icd.h exit 1  # [win]

about:
  home: https://github.com/KhronosGroup/Vulkan-Headers
  license: Apache-2.0 or MIT
  license_file:
    - LICENSES/Apache-2.0.txt
    - LICENSES/MIT.txt
  summary: Vulkan Header files and API registry.

extra:
  feedstock-name: vulkan-headers
  recipe-maintainers:
    - traversaro
